# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches:
      - main

jobs:
  publish_interest_image:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests
        
    - name: Publish Docker Image
      run: |
          # login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          # build image
          docker build . --tag ghcr.io/eclipse-researchlabs/smartclide/tdinterest:$(date +'%Y-%m-%d')
          # push image
          docker push ghcr.io/eclipse-researchlabs/smartclide/tdinterest:$(date +'%Y-%m-%d')
